app/models.py
from . import db

class Task(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(150), nullable = False)
    status = db.Column(db.String(20), default = 'Pending')
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# Create Database.

db = SQLAlchemy() 

def create_app():
    app = Flask(__name__)
    
    app.config['SECRET_KEY'] = 'Your_Secret_Key'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///Todo.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False
    
    db.__init__(app)
    
    from .auth import auth
    from .views import views
    
    app.register_blueprint(views,url_prefix='/')
    app.register_blueprint(auth,url_prefix='/')
    

    
    with app.app_context():
        from app.models import Task
        db.create_all()
    
    return app

app/auth.py
from flask import Blueprint, render_template, redirect, request, url_for, session, flash

auth = Blueprint('auth', __name__)

USER_CREDENTIAL = {
    'username': 'admin',
    'password': '1234'
}

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        
        if username == USER_CREDENTIAL['username'] and password == USER_CREDENTIAL['password']:
            session['user'] = username
            flash('Login successful!', 'success')
            return redirect(url_for('views.view_tasks'))  
        else:
            flash("Invalid username or password. Try again!", 'danger')
    
    return render_template('login.html')

@auth.route('/logout')
def logout():
    session.pop('user', None)
    flash('Logged out successfully!', 'info')
    return redirect(url_for('auth.login'))  

            
    

app/views.py
from flask import Blueprint, render_template, redirect, request, url_for, session, flash
from app import db
from .models import Task

views = Blueprint('views', __name__)

@views.route('/')
def view_tasks():
    if 'user' not in session:
        return redirect(url_for('auth.login'))

    tasks = Task.query.all()
    return render_template('home.html', tasks=tasks)

@views.route('/add_tasks', methods=["POST"])
def add_tasks():
    if 'user' not in session:
        return redirect(url_for('auth.login'))

    title = request.form.get('title')
    if title:
        new_task = Task(title=title, status='Pending')
        db.session.add(new_task)
        db.session.commit()
        flash('Task added successfully!', 'success')

    return redirect(url_for('views.view_tasks'))

@views.route('/toggle/<int:task_id>', methods=['POST'])  
def toggle_status(task_id):
    task = Task.query.get(task_id)
    if task:
        if task.status == 'Pending':
            task.status = 'Working'
        elif task.status == 'Working':
            task.status = 'Done'
        else:
            task.status = 'Pending'
        db.session.commit()

    return redirect(url_for('views.view_tasks'))

@views.route('/delete/<int:task_id>', methods=['POST'])
def del_task(task_id):
    task = Task.query.get(task_id)
    if task:
        db.session.delete(task)
        db.session.commit()
        flash('Task deleted successfully!', 'info')
    return redirect(url_for('views.view_tasks'))

@views.route('/clear', methods=['POST'])
def clear():
    Task.query.delete()
    db.session.commit()
    flash('All tasks cleared.', 'info')
    return redirect(url_for('views.view_tasks'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}To-Do App{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}" />
  </head>
  <body>
    <header>
      <div class="container">
        <h1>My To-Do App</h1>
        <nav>
          <a href="{{ url_for('views.view_tasks') }}">Home</a>
          {% if session.get('user') %}
            <a href="{{ url_for('auth.logout') }}">Log Out</a>
          {% else %}
            <a href="{{ url_for('auth.login') }}">Log In</a>
          {% endif %}
        </nav>
      </div>
    </header>

    <main class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="flash {{ category }}">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}{% endblock %}
    </main>

    <footer>
      <div class="container">
        <p>&copy; 2025 My Flask To-Do App</p>
      </div>
    </footer>
  </body>
</html>

app/templates/home.html
{% extends 'base.html' %} {% block title %} Task {% endblock title %} {% block
content %}
<div class="task-box">
  <h2>Your Tasks</h2>
  <form action="{{url_for('views.add_tasks')}}" method="POST" class="task-form">
    <input type="text" name="title" placeholder="New Task" required />
    <button type="submit" class="btn">Add</button>
  </form>
  {% if tasks %}
  <form action="{{url_for('views.clear')}}" method="POST">
    <button type="submit" class="btn btn-clear">Clear All Tasks</button>
  </form>
  <br />
  <table class="task-table">
    <thead>
      <tr>
        <th>Sr.no</th>
        <th>Task</th>
        <th>Status</th>
        <th>Change</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ task.title }}</td>
        <td>
          <span class="badge {{task.status|lower}}">{{task.status}}</span>
        </td>
        <td>
          <form
            action="{{url_for('views.toggle_status',task_id =task.id)}}"
            method="POST"
          >
            <button class="btn-small" type="submit">Next</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No Task Yet. Add One Above!</p>
  {% endif %}
</div>
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock title %}

{% block content %}
    <div class="login-box">
        <h2>login</h2>
        <form method="POST">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" required>
            </div>

             <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
            </div>
            <button type="submit" class="btn">LogIn</button>
        </form>
    </div>
{% endblock content %}